package Hangman_Game;


/**
* Hangman_Game/Hangman_InterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman_Game.idl
* Monday, May 7, 2018 12:07:31 PM CST
*/

public interface Hangman_InterfaceOperations 
{
  boolean login (String username);
  String wordToGuess (String username);
  boolean guessTheLetter (String letter);
  void logout (String username);
} // interface Hangman_InterfaceOperations
