package Hangman_Game;

/**
* Hangman_Game/Hangman_InterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman_Game.idl
* Monday, May 7, 2018 12:07:31 PM CST
*/

public final class Hangman_InterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Hangman_Game.Hangman_Interface value = null;

  public Hangman_InterfaceHolder ()
  {
  }

  public Hangman_InterfaceHolder (Hangman_Game.Hangman_Interface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Hangman_Game.Hangman_InterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Hangman_Game.Hangman_InterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Hangman_Game.Hangman_InterfaceHelper.type ();
  }

}
