package Hangman_Game;


/**
* Hangman_Game/Hangman_Interface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman_Game.idl
* Tuesday, 8 May 2018 at 3:09:08 PM Singapore Standard Time
*/

public interface Hangman_Interface extends Hangman_InterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hangman_Interface
