package Hangman_Game;


/**
* Hangman_Game/Hangman_Interface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman_Game.idl
* Saturday, May 12, 2018 5:43:56 AM CST
*/

public interface Hangman_Interface extends Hangman_InterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hangman_Interface
