package Hangman_Game;


/**
* Hangman_Game/Hangman_InterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman_Game.idl
* Saturday, May 12, 2018 5:43:56 AM CST
*/

public interface Hangman_InterfaceOperations 
{
  boolean login (String username);
  String wordToGuess (String username);
  void logout (String username);
} // interface Hangman_InterfaceOperations
