# Python stubs generated by omniidl from ..\Hangman_Game.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Hangman_Game"
#
__name__ = "Hangman_Game"
_0_Hangman_Game = omniORB.openModule("Hangman_Game", r"..\Hangman_Game.idl")
_0_Hangman_Game__POA = omniORB.openModule("Hangman_Game__POA", r"..\Hangman_Game.idl")


# interface Hangman_Interface
_0_Hangman_Game._d_Hangman_Interface = (omniORB.tcInternal.tv_objref, "IDL:Hangman_Game/Hangman_Interface:1.0", "Hangman_Interface")
omniORB.typeMapping["IDL:Hangman_Game/Hangman_Interface:1.0"] = _0_Hangman_Game._d_Hangman_Interface
_0_Hangman_Game.Hangman_Interface = omniORB.newEmptyClass()
class Hangman_Interface :
    _NP_RepositoryId = _0_Hangman_Game._d_Hangman_Interface[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Hangman_Game.Hangman_Interface = Hangman_Interface
_0_Hangman_Game._tc_Hangman_Interface = omniORB.tcInternal.createTypeCode(_0_Hangman_Game._d_Hangman_Interface)
omniORB.registerType(Hangman_Interface._NP_RepositoryId, _0_Hangman_Game._d_Hangman_Interface, _0_Hangman_Game._tc_Hangman_Interface)

# Hangman_Interface operations and attributes
Hangman_Interface._d_login = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
Hangman_Interface._d_wordToGuess = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
Hangman_Interface._d_guessTheLetter = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
Hangman_Interface._d_logout = (((omniORB.tcInternal.tv_string,0), ), (), None)

# Hangman_Interface object reference
class _objref_Hangman_Interface (CORBA.Object):
    _NP_RepositoryId = Hangman_Interface._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_Hangman_Game.Hangman_Interface._d_login, args)

    def wordToGuess(self, *args):
        return self._obj.invoke("wordToGuess", _0_Hangman_Game.Hangman_Interface._d_wordToGuess, args)

    def guessTheLetter(self, *args):
        return self._obj.invoke("guessTheLetter", _0_Hangman_Game.Hangman_Interface._d_guessTheLetter, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_Hangman_Game.Hangman_Interface._d_logout, args)

omniORB.registerObjref(Hangman_Interface._NP_RepositoryId, _objref_Hangman_Interface)
_0_Hangman_Game._objref_Hangman_Interface = _objref_Hangman_Interface
del Hangman_Interface, _objref_Hangman_Interface

# Hangman_Interface skeleton
__name__ = "Hangman_Game__POA"
class Hangman_Interface (PortableServer.Servant):
    _NP_RepositoryId = _0_Hangman_Game.Hangman_Interface._NP_RepositoryId


    _omni_op_d = {"login": _0_Hangman_Game.Hangman_Interface._d_login, "wordToGuess": _0_Hangman_Game.Hangman_Interface._d_wordToGuess, "guessTheLetter": _0_Hangman_Game.Hangman_Interface._d_guessTheLetter, "logout": _0_Hangman_Game.Hangman_Interface._d_logout}

Hangman_Interface._omni_skeleton = Hangman_Interface
_0_Hangman_Game__POA.Hangman_Interface = Hangman_Interface
omniORB.registerSkeleton(Hangman_Interface._NP_RepositoryId, Hangman_Interface)
del Hangman_Interface
__name__ = "Hangman_Game"

#
# End of module "Hangman_Game"
#
__name__ = "Hangman_Game_idl"

_exported_modules = ( "Hangman_Game", )

# The end.