module Hangman_Game
{
	interface Hangman_Interface
	{
		boolean login(in string username);
		string wordToGuess(in string username);
		boolean guessTheLetter(in string letter);
		void logout(in string username);
	};
};