# DO NOT EDIT THIS FILE!
#
# Python module Hangman_Game generated by omniidl

import omniORB
omniORB.updateModule("Hangman_Game")

# ** 1. Stub files contributing to this module
import Hangman_Game_idl

# ** 2. Sub-modules

# ** 3. End
