package Hangman_Game;


/**
* Hangman_Game/Hangman_InterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Hangman_Game.idl
* Tuesday, 8 May 2018 at 3:09:09 PM Singapore Standard Time
*/

public interface Hangman_InterfaceOperations 
{
  boolean login (String username);
  String wordToGuess (String username);
  void logout (String username);
} // interface Hangman_InterfaceOperations
