module Hangman_Game
{
	interface Hangman_Interface
	{
		boolean login(in string username);
		string wordToGuess(in string username);
		boolean isGuessCorrect(in string username, in string letter);
		string getLife(in string username);
		boolean isGameOver(in string username);
		void logout(in string username);
	};
};